name: Build and Store Artifact

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11, macos-12, macos-13, macos-14]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: make

      - name: Run test
        run: |
          output=$(./nowplaying-cli get-raw)
          if [ $? -ne 0 ]; then
            echo "Command failed"
            exit 1
          fi
          if [ "$output" != "(null)" ]; then
            echo "Unexpected output: $output"
            exit 1
          fi

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nowplaying-cli-${{ matrix.os }}
          path: ./nowplaying-cli
